name: Run Unit Tests
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
  test:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
            go: [1.22.*]
    runs-on: ${{ matrix.os }}
    name: Setup Tests
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: go test -v ./...

